libjxl skipped of win32 due to multiple definition
See the multiple definitions which breaks linking to FFmpeg:

```
/opt/ct-ng/lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld: /opt/ffbuild/lib/libjxl.a(enc_adaptive_quantization.cc.obj):enc_adaptive_quantization.cc:(.text$fabs[_fabs]+0x0): multiple definition of `fabs'; /opt/ct-ng/i686-w64-mingw32/sysroot/mingw/lib/../lib/libmingwex.a(lib32_libmingwex_a-fabs.o):/ct-ng/build/i686-w64-mingw32/src/mingw-w64/mingw-w64-crt/math/fabs.c:17: first defined here
```

I will figure out if I can change fabs definition to libjxl with patch or something...

- Martin Eesmaa